u-boot: whitelist USB_DWC3 config
The CONFIG_USB_DWC3 ad-hoc config needs to be whitelisted to avoid the
following build failure:

| Error: You must add new CONFIG options using Kconfig
| The following new ad-hoc CONFIG options were detected:
| CONFIG_USB_DWC3

Changelog-entry: Fix u-boot compilation error by whitelisting config entries
Signed-off-by: Alex Gonzalez <alexg@balena.io>